### ISSUE TITLE
Mobile BigText field not showing Lookup

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#1]
In mobile mode bigtext fields aren't populating the dropdown functionality, they are showing as purely text fields.

**Comment by paulfisher53** [comment]
[Fix.zip](https://github.com/LiveappSolutions/Liveapp/files/715562/Fix.zip)

Fixed. Merge the attached zip.

**Comment by paulfisher53** [comment]
Will be release in v4.2-CU5
