### ISSUE TITLE
Chrome incorrectly interprets fields as username/password in Partner Portal 

### ISSUE THREAD

**Issue by adamLiveware** [LiveappSolutions/Liveapp#11]
Using Chrome, when I login to https://dev.liveapp.com.au/Partner and open a license card, Chrome will auto-fill Auth Code with username and Password with password if I have saved the login credentials for the site into Chrome. I am not very familiar with how Chrome (and other browsers) determine whether fields are username/password fields, but I have read that for Chrome:
- The password field must have `type="password"`
- The username field must have `type="username"`

I don't know if that's the only way Chrome decides the mapping, and I have no idea about other browsers, but considering that the page updates automatically and Chrome wrote into those fields despite the fact they already had data, I consider this issue to be critical. 

We need to know whether this issue is specific to the dev.liveapp.com.au/Partner site or if it potentially could affect other sites built on the framework, because it would cause some serious problems if data is overwritten without prompting the users. Also please try to identify which version was first affected.

**Comment by paulfisher53** [comment]
Hi Adam, I've read about this issue and I think I have a fix for it. As I can't replicate the issue on my version of chrome, can you please give it a test for me? I have applied the fix to the partner portal

**Comment by adamLiveware** [comment]
My version of Chrome is 57.0.2987.98, are you using an earlier version?

I opened MAIWELTEST and LIVEDEMO and it is now ok with a saved password. I also tried in Firefox and it’s fine too, and I would have with IE but I can’t figure out how to get it to save the credentials. Perhaps the login form is not complying to the requirements for IE to save the credentials.

How much can you tell us about the cause or what version it started with? I need to know whether this will be an issue in any of our sites.

Thanks,

Adam Shortall
Senior Software Engineer|': 02 4921 8333 | 6: 02 4920 8500 |
www.liveware.com.au<http://www.liveware.com.au/> | Suite 9, 29 Smith Street Charlestown NSW 2290 |
[Liveware ERP Email Signature]

**Comment by paulfisher53** [comment]
Chrome automatically tries to autofill password fields and the field directly before it (thinking it's a username field). I have added a fix to add an attribute to password fields so this does not happen.

Please merge this [Fix.zip](https://github.com/LiveappSolutions/Liveapp/files/912415/Fix.zip)
