### ISSUE TITLE
Jquery multiselect.js Bug

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#12]
When customers try to deselect a client from the dropdown in roster shifts they have to click each one manually (including all groups). 

Look at newest version on github https://github.com/ehynds/jquery-ui-multiselect-widget to see if there is a fix and if the newest version is stable

**Comment by paulfisher53** [comment]
Fixed. I have changed the control to "refresh" instead of "update" when clicking the checkboxes

[MultiComboFix.zip](https://github.com/LiveappSolutions/Liveapp/files/1120996/MultiComboFix.zip)

**Comment by paulfisher53** [comment]
I've replaced all the "updates" with "refresh". Please load this fix in and give it a test. Remember to refresh the instance 

[MultiselectFix.zip](https://github.com/LiveappSolutions/Liveapp/files/1168724/MultiselectFix.zip)
