### ISSUE TITLE
FilterToolbar.js Modifications

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#13]
A request from Apps for filters to be split and individually removable, similar to NAV. Example below. If this isn't workable for both functionality and site layout reasons (across all sites and pages) please provide feedback.

![filtertoolbar](https://cloud.githubusercontent.com/assets/25164973/24177369/2dc92910-0ef6-11e7-9f34-0f2cb5dff625.PNG)

**Comment by paulfisher53** [comment]
Done, please load the attached mod. I have split the filters into individual buttons. If you click the filter, it will allow you to edit on the right side. If you click the individual "x" it will clear just that filter.

[FilterToolbarMods.zip](https://github.com/LiveappSolutions/Liveapp/files/1237658/FilterToolbarMods.zip)

**Comment by JasonBev** [comment]
New feature added and working as expected - no further action required.
