### ISSUE TITLE
Multi Line Progress Note Graph

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#14]
Item 2170 you stated this will need a plugin for chartist.js to enable this functionality needed (separate line graphs into note types)

**Comment by JasonBev** [comment]
As discussed we require a noticable different colour for each subsequent line (3 in this case) and a tooltip to display which note type is which.

**Comment by paulfisher53** [comment]
Done. Please merge in the attached mod:

[GraphMod.zip](https://github.com/LiveappSolutions/Liveapp/files/982342/GraphMod.zip)
