### ISSUE TITLE
Exif data rotating images

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#15]
On upload of a client image that appears vertical but contains exif data from an iphone it is rotated horizontally.

Look into manual rotation or updated versions of croppic.js and canvasresize.js or utilising a new currently maintained 3rd-party app.

Edit - Removed example image with exif data

**Comment by paulfisher53** [comment]
Done. I have used a library called cropper:

https://fengyuanchen.github.io/cropper

I have added rotate and zoom to the control. If you need more I can add them in.

Here is the fix zip: [CropperFix.zip](https://github.com/LiveappSolutions/Liveapp/files/1120916/CropperFix.zip)
