### ISSUE TITLE
Data access layer - Date format issue

### ISSUE THREAD

**Issue by jaffars** [LiveappSolutions/Liveapp#16]
This issue is been noticed while modifying a record in roster page.

Need changes in LiveApp framework. Since the where condition for date format provided is not fetching a record

- Query not working
- 
UPDATE [RosteredShifts] SET [Date] = '20170604 12:00:00 AM',[Start] = '20170604 08:00:00 AM',

[End] = '20170604 04:00:00 PM',[Add] = 0,[Sleepover] = 0 WHERE ([RosterID] = 20) AND ([StaffID] = 36) AND ([ShiftID] = 41) AND ([Date] = '20170704 12:00:00 AM');

If we change the [Date] = '2017-04-07 00:00:00.000' then the record is getting update

Need paul assistance to make a change in Liveapp.

**Comment by paulfisher53** [comment]
Hey Jaffar,
Are you able to post the javascript code that is performing the modification so I can replicate the issue?

**Comment by JasonBev** [comment]
m_record.ShiftID = shiftid;
                            m_record.StaffID = staffid;
                            m_record.Start = ev.start_date;
                            m_record.End = ev.end_date;
                            m_record.Date = new Date(ev.start_date.getFullYear(), ev.start_date.getMonth(), ev.start_date.getDate(), 0, 0, 0);
                            m_record.Notes = ev.notes;
                            m_record.ReasonID = GetID(ev.callinreason, m_reasons);
                            m_record.WorkPlaceID = GetID(ev.workplace, m_workplaces);                            
                            m_record.RosteredHours = ev.rostered_hours;
                            m_record.BreakStartTime = ev.break_start_time;
                            m_record.Sleepover = ev.sleepover;
                            return m_record.Modify(true);

**Comment by JasonBev** [comment]
When the culture is changed, it works correctly...

I have resolved this issue by making a web.config change.
<globalization uiCulture="en" culture="en-AU" />

**Comment by paulfisher53** [comment]
Hi @jaffars ,

I have created a fix in the server DLL's. It will now format the date as "yyyy-MM-dd HH:mm:ss".

Please load the attached zip into the bin folder:

[bin.zip](https://github.com/LiveappSolutions/Liveapp/files/982264/bin.zip)
