### ISSUE TITLE
Consecutive NoteBox fields in Card Page

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#17]
If you have ordered 2 or more consecutive fields on a page that have their label hidden and are noteboxes they cause the issue in image below.

Page Type: Card
Field Type: BigText
Custom Control: NotesBox
Option: hidelabel;rows:3

![image](https://cloud.githubusercontent.com/assets/25164973/26381627/8a3c4b10-4069-11e7-8af2-55824cecadf9.png)

Those are 3 consecutive fields on the left falling on the same table row, and 3 on the right

**Comment by paulfisher53** [comment]
Please load this fix and refresh the instance:

[NotesBoxFix.zip](https://github.com/LiveappSolutions/Liveapp/files/1168737/NotesBoxFix.zip)

**Comment by JasonBev** [comment]
Fix applied - Display Issues reported now resolved
