### ISSUE TITLE
Tabbing Out of Increment Field Clears Visually

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#18]
If you tab out of a cell (as defined below) rather than mouse click out it will clear the value from view in that cell, (not delete from the DB) and a refresh will show the value again.

Page Type: List
Field: Decimal - Editable
Field Options - Delta = 0.25, Totals = True

Err msg thrown in console: Cannot read property 'v' of undefined.
Related to JQGrid - restoreCell function

![image](https://cloud.githubusercontent.com/assets/25164973/26534650/c36a4c9e-4469-11e7-83aa-08f11de28d95.png)

**Comment by paulfisher53** [comment]
Try this fix and refresh the instance:

[IncrementFix.zip](https://github.com/LiveappSolutions/Liveapp/files/1168845/IncrementFix.zip)

**Comment by JasonBev** [comment]
File uploaded > Fix for reported issue works, tab behaviour as expected
