### ISSUE TITLE
Email Log Filter

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#19]
Liveware are interested in adding a filter option (OptionsWindow) to the liveapp handled email log page, due to long loading times/timeout errors if the log has a large amount of records.

The filters requested were - Status, Date to Send, Date Sent, User, To Address, From Address and Subject

**Comment by paulfisher53** [comment]
Done. Please load the object file below:

[PAGE Xpress Email Log.zip](https://github.com/LiveappSolutions/Liveapp/files/1319979/PAGE.Xpress.Email.Log.zip)

Please let me know if this is what you want

**Comment by JasonBev** [comment]
Testing have returned with these notes-

1. duplicates caused by windows username 
3. when the filters were adjusted from the email log and ok is clicked the user is was taken to the last tab that they have open. the user should stay on the Email Log page. 
2. previous filters should remain
5. Is it possible to have users be able to type a single word from the subject rather than it have to be exact ie can users type 'incident' instead of 'cimsability incident report notification'?

DEV Notes-

1. This is the way it's stored in the Xpress User table, and can store both types in the Xpress Email Log table (login and windows types), so requires both logins to show in the list, please confirm
3. I believe this is a common issue around the application, which I workaround by passing in 
`return options.Open(viewer);` instead of `return options.Open();`

**Comment by paulfisher53** [comment]
1. Do you have an example of the duplication? It should only have 1 record for the logged in user.
2. Fixed (load file below).
3. Done (load file below).
4. I have added a wildcard to the start and end of the Subject, To Address and From Address filters (load file below).

[PAGE Xpress Email Log.zip](https://github.com/LiveappSolutions/Liveapp/files/1370696/PAGE.Xpress.Email.Log.zip)

**Comment by JasonBev** [comment]
2,3,4 - All working as expected

1. See screenshots below. Admin is the username, Liveware\Jasonb is the windows username for the same user. 

![image](https://user-images.githubusercontent.com/25164973/31526456-a236b3c2-b012-11e7-9d49-0b08def2739a.png)

![image](https://user-images.githubusercontent.com/25164973/31526466-b22e74fe-b012-11e7-94c3-aa2d7af8f0bd.png)

**Comment by paulfisher53** [comment]
Yeah. Technically they are separate users in the system (it doesn't know that they are linked)
