### ISSUE TITLE
Reports - Images overlapping when email/PDF is used

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#2]
This bug was found at HWNS (Item no; 2156)
Further R & D is required to fix the overlapping of headers (images) for all Reports. This problem is happening when using the Email PDF feature in the report. 

In previous item there was a fix found for the images to show but this would be an issue with all reports for hwns that use those images, and possibly all sites (haven't checked) relating to exporting to pdf. 

We looked at updating the client that handles the pdf conversion when emailed but didn't fix the issue with those or the headers overlapping, will require some r&d.

![image](https://cloud.githubusercontent.com/assets/25164973/22005986/bc158e56-dcbb-11e6-888a-68f789d03e0a.png)

**Comment by paulfisher53** [comment]
This is an issue with a 3rd party library. Currently the issue is under review by their team.

Until they release a new version I could load a work-around bug fix that would remove the header on page 2 and onward when sending as an email. 

Do you want me to do that?

**Comment by JasonBev** [comment]
Yes please.

**Comment by paulfisher53** [comment]
Developed a work around as per my last comment. 

Please load this [Fix.zip](https://github.com/LiveappSolutions/Liveapp/files/733595/Fix.zip)
