### ISSUE TITLE
HTTP_PREFIX Setting

### ISSUE THREAD

**Issue by paulfisher53** [LiveappSolutions/Liveapp#22]
What is the purpose of the HTTP_PREFIX setting? We have a customer that wants to use a reverse proxy, so the connection from outside to the proxy uses SSL, but from the proxy to the web server it uses HTTP. So all calls to the web app are technically HTTP, but the URL people use is HTTPS. It seems Liveapp does not handle this the way I would expect, i.e. we need to use HTTPS for the HTTP_PREFIX setting, not HTTP. However, if we use HTTPS, we then can’t also have an HTTP address, which is what they need to use internally.
 
Why do we need this restriction? Why can’t we just turn it off so both addresses can be used at once? And why does it not behave the way I would expect when it is behind a proxy?

**Comment by paulfisher53** [comment]
I have removed this setting from the framework. Please load this DLL:

[Liveapp.Framework.Service.dll.zip](https://github.com/LiveappSolutions/Liveapp/files/1335294/Liveapp.Framework.Service.dll.zip)

**Comment by jaffars** [comment]
I have tested the funtionality of allowing HTTP and HTTPS protocol to be accessed same time in one virtual directory.The test was successful but how ever there is in impact in other feature below is the issue list identified during my initial testing.
Issue 1 – Getting below error when I try to click Admin->Files (this is happening for HTTP only,https is working fine)
 
![image](https://user-images.githubusercontent.com/27175862/30997865-fe5f4cc8-a50d-11e7-8580-80db4c2150be.png)

Issue 2 – When importing an object in Object designer,I am getting below error in both HTTP and HTTPS
 
![image](https://user-images.githubusercontent.com/27175862/30997872-049178be-a50e-11e7-927f-2d6271133284.png)

**Comment by paulfisher53** [comment]
1. Looks like a Culture issue. Try adding &lt;globalization culture="en-AU" uiCulture="en-AU" /&gt; to the system.web part of the web.config
2. The CreateFileForUpload method has been upgraded for CU8, please merge in the following client scripts: [MimeFeature.zip](https://github.com/LiveappSolutions/Liveapp/files/1370721/MimeFeature.zip)

**Comment by jaffars** [comment]
Applied the fix provided and tested both the issue mentioned above.Its working as expected.
