### ISSUE TITLE
z-index display conflict

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#24]
CU6 changes to boxy.js can cause display conflicts. See image below, the dropdown selection list is displaying behind the boxy-wrapper.

![image](https://user-images.githubusercontent.com/25164973/28153709-4fd41fd6-67ea-11e7-87c1-598d8a33e1b4.png)

boxy-wrapper returns a z-index > autocomplete menu

Please ensure the autocomplete returns a higher z-index

CU6 Changes -
Website/Scripts/jQuery/Plugins/UI/Boxy.js
zIndex: 29000
zIndex: 29999
 
Website/Scripts/jQuery/Plugins/Desktop/MCAutoComplete.js
ul.css("z-index", 30001);
ul.css("z-index", 30002);

**Comment by paulfisher53** [comment]
Added fix
