### ISSUE TITLE
Header Text Colour

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#26]
When you have a dark blue as a header colour, the remove all and add all links blend in (see image).

If there are no other possible display conflicts can the following change be made? 

.ui-widget-header a { color: #104070; }
.ui-widget-header a { color: %HEADERTEXTCOLOR%; }

line 245 for skins

![image](https://user-images.githubusercontent.com/25164973/28351856-f62f25e2-6c95-11e7-8c5f-a1df5ffaa31f.png)

**Comment by paulfisher53** [comment]
Thanks for the code fix. I've added it to all 3 skins for version 4.2-CU9 and 5.0-CU1
