### ISSUE TITLE
Allow "No Locks" during FINDSET

### ISSUE THREAD

**Issue by paulfisher53** [LiveappSolutions/Liveapp#28]
Since some tables are transactional based (Only insert not an update) it’s safe to use “with (nolock)” option after the table to eliminate the locking of tables. This will improve the performance of FINDSET drastically without locking.

Need provision to add no locks for tables while querying using FINDSET or lookups.

**Comment by paulfisher53** [comment]
I have added a new field to the Table Designer called "Options" (similar to the Page Designer). This field will allow us to add options to the table definition.

If you add the option 'nolock' (without the quotes), it will add the WITH (NOLOCK) hint to the FINDSET function for that table. (See screen shot below)

![image](https://user-images.githubusercontent.com/25142601/31751998-658c6dec-b4d4-11e7-8c1a-0bbd4a0a2ea6.png)

Please load these binaries to your website to get this functionality: [bin.zip](https://github.com/LiveappSolutions/Liveapp/files/1396934/bin.zip)

**Comment by paulfisher53** [comment]
I have added the nolock option to the Xpress Change Log Table. Please load this object file: [TABL Xpress Change Log.zip](https://github.com/LiveappSolutions/Liveapp/files/1400230/TABL.Xpress.Change.Log.zip)

**Comment by jaffars** [comment]
![image](https://user-images.githubusercontent.com/27175862/31797801-00c4672c-b57c-11e7-9c87-906fcd26b9a4.png)

I am getting above error when i am importing the change log table object.

**Comment by paulfisher53** [comment]
Looks like your missing CU8 code again just like in issue #22. Please apply the same fix

**Comment by jaffars** [comment]
After applying CU8 code i was able to import change log object but when i run the Change log report i dont see with (nolock) syntax in the query executed.Used sql profiler to verify

![image](https://user-images.githubusercontent.com/27175862/31798325-ba8ead32-b57e-11e7-8ab0-ed4b1d9502cc.png)

**Comment by paulfisher53** [comment]
Did you apply the DLL's from my first comment? When I run the Xpress Change Log table I get this:

![image](https://user-images.githubusercontent.com/25142601/31799527-4e4f52fe-b586-11e7-8e47-4056bb49a080.png)

**Comment by jaffars** [comment]
Yes i applied the dll from bin.zip.I confirmed by viewing design table page where i can see the option field for table object.

![image](https://user-images.githubusercontent.com/27175862/31799789-fb21b1d8-b587-11e7-8281-1bf867017d1f.png)

**Comment by paulfisher53** [comment]
This is an issue with your local environment. If you fix it and are still having issues with this mod, please re-open this issue
