### ISSUE TITLE
Report Headers not displaying in Xpress

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#29]
All report headers in mobile view aren't displaying their default colour as per desktop view.

![image](https://user-images.githubusercontent.com/25164973/29348200-3f63780c-8295-11e7-99e0-03785c754cb5.png)

By default Report.js references the main-title for the css which isn't present in xpress (background will show as undefined). Also the ui-widget-header has no css styling in the skins for mobile.

Suggested fixes-

Line 82 - website/pages/AppMobile.htm

"<div id="divMobileHeader" style="display: none;" data-role="header" data-theme="a" data-position="fixed" data-tap-toggle="false" data-hide-during-focus="false" **class="main-title"**>"

Add Line to (Website\skins\mobile-flat - Website\skins\mobile-classic -Website\skins\mobile-compact)

.ui-widget-header { border: 1px solid #4297d7; background: %HEADERCOLOR%; color: %HEADERTEXTCOLOR%; font-weight: bold; }

Tested result-

![image](https://user-images.githubusercontent.com/25164973/29348337-487fb90e-8296-11e7-8312-2ed38066f1c4.png)

**Comment by paulfisher53** [comment]
Thanks for the code fix. Loaded it into 4.2-CU9. 

Loaded a different code fix for 5.0-CU1:

Report.js - Line 57

Remove:
m_design += "<thead><tr style='background-color: "+$('.main-title').css('background-color')+"; color: "+$('.main-title').css('color')+"; -webkit-print-color-adjust: exact;'>%columns</tr></thead>";

Add:
m_design += "<thead><tr style='background-color: "+$('.navbar-inner').css('background-color')+"; color: "+$('.navbar').css('color')+"; -webkit-print-color-adjust: exact;'>%columns</tr></thead>";
