### ISSUE TITLE
Mobile Grid Functions

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#3]
Reported from Client Plan issue with the column header functionality not working in mobile mode. The following functions need adding-

*SetColumnCaption
*ShowColumn
*HideColumn

e.g    viewer.GetPageGrid().SetColumnCaption("Action",t.ActionLabel);

**Comment by paulfisher53** [comment]
Done.

Please load [Fix.zip](https://github.com/LiveappSolutions/Liveapp/files/733640/Fix.zip)
