### ISSUE TITLE
User Queue - Role Centre Display Overflow

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#30]
Depending on the users monitor/resolution etc the user queue once over 10 items will not show those items without scroll, somewhat hidden from user view as the containers have a max-height.

On load-
![image](https://user-images.githubusercontent.com/25164973/29499241-5a69626a-8650-11e7-82d0-6174e33f38ff.png)
 
On user scrolling down in that particular box)
![image](https://user-images.githubusercontent.com/25164973/29499243-6d2064a8-8650-11e7-940a-e40f71866d7d.png)

Looking for a more user friendly layout, if it's not workable into the framework currently please inform.

**Comment by paulfisher53** [comment]
This can be accomplished using some OnOpen code like so:

```javascript
function SmallerQueue(cont){
  cont.Container().css({
    width: '80px',
    height: '80px'
  });
  $("#bg"+cont.ID()).css({
    width: '60px',
    height: '60px',
    'line-height': '60px'
  });
  $("#img"+cont.ID()).css({    
    'font-size': '30px'
  });
  cont.Control().css({
    width: '20px',
    height: '20px',
    'line-height': '20px',
    'font-size': '10px',
    'margin-top': '-20px'
  });
  cont.Label().css({
    width: '80px',
    'font-size': '10px'
  });
}

if(!Application.IsInMobile() && $(window).width() < 2000){
  for(var i = 0; i < viewer.Page().Fields.length; i++){
    var cont = viewer.Control(viewer.Page().Fields[i].Name);
    if(cont) SmallerQueue(cont);  
  }
}
```
You can replace the 2000 with a different screen size if you wish

**Comment by JasonBev** [comment]
Resize of icons/text is an acceptable solution, no further action required.

**Comment by paulfisher53** [comment]
Thanks
