### ISSUE TITLE
Image column in progress note is cutting off for CIMSXpress

### ISSUE THREAD

**Issue by jaffars** [LiveappSolutions/Liveapp#33]
Hi Paul,

I did some debugging and identified the scenario.

-AdditionalStaffField contains an HTML value, It works fine in desktop
- Image field is the next field to AdditionalStaffField, Since there is a HTML not formed properly its getting cutdown in the table.

Code causing the Issue:- Grid.js - Mobile
in function - Add Columns in the below highlighted lines

m_cols.push({
                    name: field.Name,
                    onformat: function (val) {
                        if (val == null || val == "null") {
                            return "";
                        } else {
							if(val.toString().length > 100)
								**val = val.toString().substr(0,100)+"...";**
							if(field.CustomControl == "NotesBox")
								val = val.replace(/\<br\>/g, '\r\n');
                            return val;
                        }
                    }
                });

The Val is getting stripped to 100 character so the HTML value is cutting off and causing the Issue.Attached the screenshot of the issue

![image](https://user-images.githubusercontent.com/27175862/29648274-a147d4d2-88d0-11e7-9c77-7d789675728c.png)

**Comment by paulfisher53** [comment]
Thanks Jaffar. We already fixed this in v5 by removing these 2 lines of code:

MobileControls/Grid.js

if(val.toString().length > 100)
  val = val.toString().substr(0,100)+"...";

Please do that and see if it fixes the issue in v4

**Comment by jaffars** [comment]
Tested in CU9 and its working as expected
