### ISSUE TITLE
Grid Control- Desktop Version fixes

### ISSUE THREAD

**Issue by jaffars** [LiveappSolutions/Liveapp#34]
TFS Ticket No - 4353
- No option available to disable multiselect of rows in GRID while using Ctrl+ row selection
- When a Grid refresh, its selecting the last row in default but we want 1st row to be selected as in CIMSXpress

**Comment by jaffars** [comment]
The Grid refresh iam Mentioning is via code when after an action I refresh the Grid from Code using REFRESH function that's when I see this issue

**Comment by paulfisher53** [comment]
Here is the mod to disable row multiselect: [Fix-34.zip](https://github.com/ZoomApps/Liveapp/files/1809711/Fix-34.zip) This mods adds a new Page Option called `nomultiselect`. If you add that to a list page, it will disable the row multiselect.

As for the REFRESH issue, I cannot replicate the problem. Can you show me the code you have on your action that contains the REFRESH function?

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
