### ISSUE TITLE
multi combo does not obey hidden flag

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#35]
Type: Card
Field: BigText - Lookup:true
CustomControl: MultiCombobox

When attempting to use code on page open or on validate to hide/show a field in xpress for the above scenario it only hides the heading, not the field (dropdown). It works in desktop.

e.g
viewer.Control("FieldName").Hide();

**Comment by paulfisher53** [comment]
Please load this fix: [Fix-35.zip](https://github.com/LiveappSolutions/Liveapp/files/1577795/Fix-35.zip)

**Comment by JasonBev** [comment]
Select menu and caption now hide as expected.

**Comment by paulfisher53** [comment]
Thanks
