### ISSUE TITLE
Excess white space - Chartist Display cause

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#38]
There is large amount of white space displaying at the bottom of pages - causing a minor display issue as seen in the images. This has been identified after the CU7 release where tooltips were added for the chartist,js plugin. 

Once you hover over the graph utilising this plugin the space is removed and the tooltips show/work as intended.

![image](https://user-images.githubusercontent.com/25164973/30578175-ea7bfc8e-9d55-11e7-8296-e89b9b8fc67f.png)

![image](https://user-images.githubusercontent.com/25164973/30578185-f81f9e90-9d55-11e7-94d7-3991082821b2.png)

**Comment by paulfisher53** [comment]
Hi Jason,

Please apply this fix: [Fix-38.zip](https://github.com/ZoomApps/Liveapp/files/1809316/Fix-38.zip)

Note: This fix can be applied to v4 and v5

**Comment by JasonBev** [comment]
Fix supplied hasn't rectified issue in our development environment. 

The div for the tooltip (class chartist-tooltip) to show in is still initially loading below the copyright text at the bottom of the page. I can fix this by setting a top:100% value in css initially for this class (line 784 for styles>chartist.css), but the more prominent display issue comes when you then hover over the chart and bring up a tooltip. 

This then sets the chartist-tooltip div top property to wherever you mouse is, say 1011px for example in image provided and is an absolute positioning, so when you then click on a new page to open that chartist-tooltip div still exists with that top property set to where the mouse last was in the container and will add all the excess scroll you see. See image below for example

<img width="955" alt="capture" src="https://user-images.githubusercontent.com/25164973/37381011-501c02b0-26f8-11e8-8a41-8c99b635a8e6.PNG">

**Comment by paulfisher53** [comment]
Ahhhh, I see. Try this fix also:

[Fix-38-2.zip](https://github.com/ZoomApps/Liveapp/files/1809645/Fix-38-2.zip)

**Comment by JasonBev** [comment]
Nice simple solution, issue resolved after applying Fix-38-2

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
