### ISSUE TITLE
Mandatory fields accepts space and allowing to save

### ISSUE THREAD

**Issue by jaffars** [LiveappSolutions/Liveapp#39]
Mandatory fields are not checking for a blank value.It allows a space and accepts the data.As part of mandatory field check we want liveapp to check for a valid characters.

**Comment by paulfisher53** [comment]
Fixed. Please load these script files: [Trim Spaces Fix.zip](https://github.com/LiveappSolutions/Liveapp/files/1420750/Trim.Spaces.Fix.zip)
