### ISSUE TITLE
Filter Toolbar Revamp - Individual Lookup Fields not being removed

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#40]
Liveware has identified certain fields aren't getting removed from the filters when you click on the individual 'x'.

The issue appears to be when variable pagefield is defined it removes the FF$ from the filter name, this is needed for the other functions to reference the actual field until it comes to removing it from _base.Viewer().Filters(). 

Liveware temp fix-

Line 98 FilterToolbar.js
`return _base.Viewer().Filter(pagefield.Name, null, true);`
to
`return _base.Viewer().Filter(filter.Name, null, true);`

**Comment by paulfisher53** [comment]
Thanks for the code fix. I've added it to 4.2-CU9 & 5.0-CU1
