### ISSUE TITLE
Spinner Control: Tabbing through on a grid

### ISSUE THREAD

**Issue by paulfisher53** [LiveappSolutions/Liveapp#41]
Basically Caitlin discovered if you tab through the fields fairly quickly that are autosaving, e.g the progress note decimal fields in the image in https://github.com/LiveappSolutions/Liveapp/issues/18 it will either be delayed in updating or not update at all, it’s not user-friendly.
 
It appears there is a difference between tabbing and clicking. Tabbing runs the service again and threadend doesn’t occur until well after the load screen has gone, it creates a queue/overlap with a new threadstart and issues arise as mentioned above.

**Comment by paulfisher53** [comment]
Please load the attached fix. I have removed the on blur event from the control.

[SpinnerFix.zip](https://github.com/LiveappSolutions/Liveapp/files/1339550/SpinnerFix.zip)

**Comment by JasonBev** [comment]
Behaviour is now consistent between tabbing and clicking, user experience is improved. 
Liveware has approved the fix after testing.

**Comment by paulfisher53** [comment]
Thanks
