### ISSUE TITLE
Multiple Timepicker Functionality

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#43]
Liveapp Version - All

**Issue:** I have two fields with the type 'Time' on the same page. 

If I click to edit the first field and change the hour value it saves that but returns the second time value in the display (loops through code twice and returns the last). This is confusing to the end user as they haven't clicked to edit the 2nd field and may still want to edit the minute value.

If the intended functionality of timepicker.js is to automatically skip to the 2nd field the dropdown needs to appear below that field to make it clear.

**Page:** Optionswindow, Card

**E.g** In screenshot I have selected 3:10am as the start time after changing the hour from 2 to 3. It is now showing the End Time of 11:00pm.

![capture4](https://user-images.githubusercontent.com/25164973/32305520-24b9a1ee-bfca-11e7-9aa2-771eca448f5d.PNG)

**Comment by paulfisher53** [comment]
Hi @JasonBev , please try this fix:

[Fix-43.zip](https://github.com/LiveappSolutions/Liveapp/files/1701525/Fix-43.zip)

**Comment by JasonBev** [comment]
Testing complete and fix provided works as intended.
Nothing further required for this item.

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
