### ISSUE TITLE
filter toolbar field name clearing

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#44]
Follow up to #40 
Minor usability issue - The same flow fields have an issue when you individually clear their value (as opposed to clear all) - the field name will be removed from the dropdown instead of remaining in view.

Liveware temp fix-
line 101 - FilterToolbar.js
`m_filterFields.val(pagefield.Name);`
to
`m_filterFields.val(filter.Name);`

It will still remove the value in line 90/91 as it's looking for the value with FF$ removed but re-populates it with that fix. A cleaner solution would probably need to be applied as a permanent fix for liveapp.

**Comment by paulfisher53** [comment]
I have applied your fix to lines 91 and 101. I think all functionality is now working for filtering flowfields. 

Can you please load this fix and confirm? [Fix-44.zip](https://github.com/LiveappSolutions/Liveapp/files/1580996/Fix-44.zip)

**Comment by JasonBev** [comment]
File upload incomplete on comment, please add again/provide link.

**Comment by paulfisher53** [comment]
Sorry about that, updated...

**Comment by JasonBev** [comment]
Fix working, I think we have it all resolved now.

**Comment by paulfisher53** [comment]
Thanks
