### ISSUE TITLE
mobile calendar control missing icons

### ISSUE THREAD

**Issue by jaffars** [LiveappSolutions/Liveapp#46]
Time and Calendar controls missing next and previous month Icon in mobile display.Images below helps you.

![image](https://user-images.githubusercontent.com/27175862/32635418-6d8e7242-c604-11e7-8c93-53cc4ce7cbd1.png)

**Comment by paulfisher53** [comment]
Please load this fix: [Fix-46.zip](https://github.com/LiveappSolutions/Liveapp/files/1624603/Fix-46.zip)

**Comment by jaffars** [comment]
Thanks Paul, It has fixed partially but still couple of more icons missing.

Icon Missing for Set button
![image](https://user-images.githubusercontent.com/27175862/35205418-36c97a9a-ff89-11e7-91a3-5794b2e9a229.png)

Icon missing for "Jump to Today"

![image](https://user-images.githubusercontent.com/27175862/35205437-45c00ff0-ff89-11e7-9ab6-fa251313cb5c.png)

**Comment by paulfisher53** [comment]
Hi Jaffar,

Try this fix: [Fix-46-2.zip](https://github.com/LiveappSolutions/Liveapp/files/1654117/Fix-46-2.zip)

**Comment by jaffars** [comment]
Fix provided is working and moved for testing
