### ISSUE TITLE
service worker caching issue

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#47]
Upon implementation and testing of liveApp 5.0 we found changes to our application weren't getting passed to the user on browser refresh. On line 1047 of Application.js it wasn't returning the service-worker.js file as expected.

On test we found unless you had the url in the correct format e.g 

Url 1 - https://cims.livewarecloud.com.au/dev/

It wouldn't work, so the following would be invalid

Url 2 - https://cims.livewarecloud.com.au/dev#
Url 3 - https://cims.livewarecloud.com.au/dev

Possible solution-

` navigator.serviceWorker.register('./service-worker'+(Application.IsInMobile()?'-mobile':'')+'.js?instance='+instance)`
to
`navigator.serviceWorker.register('%SERVERADDRESS%service-worker'+(Application.IsInMobile()?'-mobile':'')+'.js?instance='+instance)`

While it will now retrieve the service-worker.js file with all 3 url formats with that change it still seems to take 2 refreshes of the browser when using url 2 or 3 to get the updated version. We will continue testing but see if you receive the same behaviour.

**Comment by paulfisher53** [comment]
Jason, I have added your fix to the repo. 

As for your refresh issue, I could not replicate it. Please clear your app in Chrome Dev Tools:

Application Tab > Clear Storage > Clear Site Data - This will remove any older service workers which might be causing your issue

Also, each time you do an Instance refresh (Dashboard > Instance > OK), make sure you wait a few seconds to give the service worker time to download and install the update (you can see the progress of this in Chrome Dev Tools > Application Tab > Service Workers).

**Comment by JasonBev** [comment]
I can see the new service worker installing - then receive the message in console 'Content is available offline' as installingWorker.state is 'activated'.

On refresh the site (i.e login screen) is loaded before some of the Application Cache Progress events are finished (e.g css and js). The Application cache UpdateReady then appears so you need to refresh a 2nd time to get all the new changes.

This was just a basic test with changing header colours in chrome for desktop. Mobile doesn't have the same issue.

**Comment by paulfisher53** [comment]
That's weird. In `Application.js` on line 1045 it checks if `serviceWorker` is available. If it isn't, then it will use Application Cache. Can you debug and make sure it isn't hitting the Application Cache code? It should hit the top section of the `if` statement (it will log when the update is finished with 'Content is now available offline!')

**Comment by JasonBev** [comment]
It doesn't appear to be hitting that code, no. Just sending the console log so you can see, the one on the left is the first refresh after the service worker is installed, one on the right in the next refresh. 

![cache](https://user-images.githubusercontent.com/25164973/34657904-d0174fe4-f47e-11e7-8bfc-32dd62d3620d.png)

What calls that application cache downloading event?

**Comment by paulfisher53** [comment]
It seems that is called automatically when the page loads (I'm currently trying to find a way to stop that). This should not effect the serviceWorker. Can you screenshot the "Application > Service Workers" tab?

**Comment by JasonBev** [comment]
Sure. One on the left is when I've made a change to the instance and the new service worker is installing (takes a few seconds). One on the right is now installed. This all happens before the console image above.

![serviceworker](https://user-images.githubusercontent.com/25164973/34800256-1563b6d4-f6b7-11e7-8a15-84cc2845fd6e.png)

**Comment by paulfisher53** [comment]
Are you on the login screen? The auto update doesn't run until you are logged in (after login a timer is kicked off which will check the instance file every 30 seconds for an update)

**Comment by paulfisher53** [comment]
Also, I've removed the appcache (as keeping it was essentially double downloading the web app). In case that was causing the issue, I suggest you load this fix: [Fix-47.zip](https://github.com/LiveappSolutions/Liveapp/files/1624488/Fix-47.zip)

**Comment by JasonBev** [comment]
Success! Application is now working as designed/expected with the fix supplied.

**Comment by paulfisher53** [comment]
Nice! Thanks
