### ISSUE TITLE
Give option of disabling 'close' function on save of page- Mobile 

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#49]
View - mobile
Object - page

There are certain scenarios  (i.e show a button on insert validation) where we would like the option of being able to have the user click the save button (i.e check icon) and have the page stay open/refresh as opposed to the automatic close of page and revert back to parent.

This provides a better customisable user friendly experience.

**Comment by paulfisher53** [comment]
I've added a new page option `saveonly`. This will tell the page to save and not close when the tick is clicked in mobile mode.

Fix: [Fix-49.zip](https://github.com/LiveappSolutions/Liveapp/files/1650800/Fix-49.zip)

**Comment by jaffars** [comment]
Tested and can be closed

**Comment by paulfisher53** [comment]
Thanks
