### ISSUE TITLE
Date field not stripping time on insert

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#5]
Progress notes entered are leaving a time stamp of when the user entered the note despite it being a time field (not a datetime), we need to have it strip the time part in the framework as it is causing issues with sorting/order by.

**Comment by paulfisher53** [comment]
Fixed. Please merge this [Fix.zip](https://github.com/LiveappSolutions/Liveapp/files/746115/Fix.zip)
