### ISSUE TITLE
Mobile/Tablet Display Issue - Soft keyboard on Andriod covering field -5.0

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#50]
It has been identified in testing 5.0 that when a user clicks on a free typing field and the device keyboard displays it covers the field the user clicked on and are required to try and scroll to bring it back into view.

Desired implementation would be - automatically panned

**Comment by jaffars** [comment]
Mobile/Tablet View - IOS and Android - The textbox hidden behind the Keypad

Usability issue has been identified in most of the Form entries especially for the Textboxes which are at the bottom of the screen.Most of the time the text box hide behind the keypad.

Resolution - Push the element to be edited above the keypad so the user can able to view what field it been entered as well as the text typed in.

**Comment by paulfisher53** [comment]
Hi @jaffars & @JasonBev , please apply this fix:

[Fix-50.zip](https://github.com/LiveappSolutions/Liveapp/files/1701629/Fix-50.zip)

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
