### ISSUE TITLE
Report Icons aren't displaying on Print - 5.0+

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#51]
The new material design icons in reports are displaying fine in the application but not in print/print preview.

e.g
In application-
![image](https://user-images.githubusercontent.com/25164973/33190909-b67fb4cc-d106-11e7-971d-724088fd42e9.png)

Print preview-
![image](https://user-images.githubusercontent.com/25164973/33190912-cedfa0cc-d106-11e7-97fa-b25709b507e0.png)

Specs-
Liveapp Version - 5.0+
Browser - Chrome/IE
Device - Desktop

Code -
`UI.IconImage("check2")`
`<i class="mdi mdi-check-circle" style="font-size: 15px"></i>`

**Comment by paulfisher53** [comment]
Hi @JasonBev , please apply this fix:

[Fix-51.zip](https://github.com/LiveappSolutions/Liveapp/files/1701671/Fix-51.zip)

**Comment by JasonBev** [comment]
Testing complete and fix provided works as intended.
Nothing further required for this item.

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
