### ISSUE TITLE
Mobile Loader not displaying - 5.0+

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#52]
Version - 5.0+
Mode: Mobile

In desktop there is a visual loader with a % on each individual tab within a page. i.e navigating back to the dashboard

In mobile there is no visual representation to the end user that there are still threads (i.e TableFetch) open and can cause inconsistencies with their experience.

**Comment by paulfisher53** [comment]
Hi Jason,

Please load this mod: [Fix-52.zip](https://github.com/ZoomApps/Liveapp/files/1809259/Fix-52.zip)

**Comment by JasonBev** [comment]
Fix uploaded and working as expected.

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
