### ISSUE TITLE
incorrect action bar position in mobile

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#54]
The action bar is calculated to be fixed from the top 100vh - 60px (height of bar) which works, but on change of orientation it remains at that fixed point, not at the bottom of the screen.

![image](https://user-images.githubusercontent.com/25164973/33750882-013ed93c-dc2b-11e7-89cf-3e8a248df180.png)

![image](https://user-images.githubusercontent.com/25164973/33750899-1406467c-dc2b-11e7-916f-6a469a87c228.png)

Possibly change mobilewindow.js and skin (.actions-bar-bottom) to use bottom:0px instead, or a-

    $(window).on("orientationchange", function() {
      $("#" + m_id + "actions").css("top","calc(100vh - 60px)")
    });

**Comment by paulfisher53** [comment]
I've changed all top styles to bottom. Please give it a test

[Fix-54.zip](https://github.com/LiveappSolutions/Liveapp/files/1581120/Fix-54.zip)

**Comment by JasonBev** [comment]
Tested and solution provided works  as expected.

**Comment by paulfisher53** [comment]
Thanks
