### ISSUE TITLE
Non-Editable fields removed from view - Mobile

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#55]
Issue with non-editable fields getting removed from view completely in mobile when editing/creating new record, either through the page editor setting or through code (i.e viewer.Control("ID").Enabled(false), no issue with the grid functionality.

**Comment by paulfisher53** [comment]
Hi @JasonBev , please apply this fix:

[Fix-55.zip](https://github.com/LiveappSolutions/Liveapp/files/1701688/Fix-55.zip)

**Comment by JasonBev** [comment]
Testing complete and fix provided works as intended.
Nothing further required for this item.

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
