### ISSUE TITLE
Mandatory Date fields - Grid

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#56]
Mandatory date fields in grid will display as NaN/NaN/NaN instead of the text 'mandatory'

Liveapp applied a fix for liveware previously, this appears to have been lost from your source code so sending it through if you wish to include.

Fix below-

![image](https://user-images.githubusercontent.com/25164973/33866324-20be6d64-df4a-11e7-9884-bcf001195d1b.png)

**Comment by paulfisher53** [comment]
Thanks for the fix Jason. I have added it to the source
