### ISSUE TITLE
Webservice: New Overridable Function

### ISSUE THREAD

**Issue by paulfisher53** [LiveappSolutions/Liveapp#57]
Add a new overridable function to the webservice class that fires on GetServerInfo in the Server Endpoint. 

This will allow framework extensions to run server side code each time the server is pinged from the Liveapp Service

**Comment by paulfisher53** [comment]
Hi @jaffars, please load this mod for Adam:

[Fix-57.zip](https://github.com/LiveappSolutions/Liveapp/files/1718187/Fix-57.zip)

**Comment by jaffars** [comment]
Hi Paul,

Does Fix-57.Zip also includes the changes you made for #69.I could see framework.service.dll is common in both the fix

Jaffar Sadiq | B.COM(Commerce)|
Senior Software Developer |': 02 4921 8333 | 6: 02 4920 8500 |
www.liveware.com.au<http://www.liveware.com.au/> | Suite 9, 29 Smith Street Charlestown NSW 2290 |
[Liveware ERP Email Signature]

**Comment by paulfisher53** [comment]
Yeah. Load #69 first, then load this one over the top

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
