### ISSUE TITLE
Unable to link to page from Chart/Graph

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#58]
Prior to https://github.com/LiveappSolutions/Liveapp/releases/tag/v4.2-CU7 release we could combine the chart and drilldown custom controls to give the ability to the user to click on the graph and be taken to a specified page.

The addition of tooltips from https://github.com/LiveappSolutions/Liveapp/issues/14 appears to have broken this functionality.

**Comment by paulfisher53** [comment]
Hi @JasonBev , please try this fix:

[Fix-58.zip](https://github.com/LiveappSolutions/Liveapp/files/1701786/Fix-58.zip)

**Comment by JasonBev** [comment]
Testing complete and fix provided works as intended.
Nothing further required for this item.

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
