### ISSUE TITLE
On delete flag not resetting after Error

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#6]
Incident Config page. If you get an error due to table keys not being unique (severity/likelihood) for overall risk calculation and then try to delete that row it remains there until you re-open the page.

The default delete functionality needs to be enabled after an error occurs.

**Comment by paulfisher53** [comment]
Done. A flag was not getting reset correctly on error. Please load this [Fix.zip](https://github.com/LiveappSolutions/Liveapp/files/769022/Fix.zip)
