### ISSUE TITLE
Tablet View - When there is a long list to be shown on a multiselect the list is not setting the value back after selecting

### ISSUE THREAD

**Issue by jaffars** [LiveappSolutions/Liveapp#61]
In tablet view, when the ‘x’ button is hit after selecting multiple items in a multi select control, it closes the popup of list box as well as the subpage. It should only close the pop up of list box and not the subpage as well. 

This only happens when you have a large number of items to select in the multi select. If you could prioritise this as we are unable to release a version with this issue as it affects one of our key features

![image](https://user-images.githubusercontent.com/27175862/34921933-fd58dafa-f9dc-11e7-9028-89b855f6fb80.png)

**Comment by paulfisher53** [comment]
I believe that jquery mobile hash listening is to blame. Please load this fix: [Fix-61.zip](https://github.com/LiveappSolutions/Liveapp/files/1633170/Fix-61.zip)

**Comment by jaffars** [comment]
Issue fixed and verified
