### ISSUE TITLE
Tablet View - design and usability issues due to orientation 

### ISSUE THREAD

**Issue by jaffars** [LiveappSolutions/Liveapp#62]
iPad

1. Found that when i rotate the orientation of the screen from portrait to landscape that the screen appears as below and i am unable to scroll to see the form. I expect that i should be able to rotate the orientation of the iPad and still be able to continue entering the form fields.
 
![image](https://user-images.githubusercontent.com/27175862/34964692-e495e708-faa2-11e7-8eb2-2eb4b73c9097.png)

Android

2. Found that when i am entering data into fields , i am unable to see what i am typing due to the fact that the keyboard appears over the field. I expect that i should be able to both see what i am typing into the field and be able to see the keyboard at the same time. 

![image](https://user-images.githubusercontent.com/27175862/34964723-084b3cde-faa3-11e7-88b3-84307d1ea13b.png)

3. When entering a data into a form,  i found that there is loads of white space to the right of the form. I expect that there should be little to no white space. Note that this is the case for both devices and the below snip is from the Android

![image](https://user-images.githubusercontent.com/27175862/34964760-375227e0-faa3-11e7-8189-1407657447ac.png)

**Comment by paulfisher53** [comment]
Hi Jaffar,

Please load this fix for the orientation issues: [Fix-62.zip](https://github.com/ZoomApps/Liveapp/files/1827422/Fix-62.zip)

The keyboard issue should be fixed with #50 , so make sure that is loaded also

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
