### ISSUE TITLE
Mobile/Tablet Display - IOS devices - List box single select not bringing the Keyboard when tapped  'Type here to Search'  text field

### ISSUE THREAD

**Issue by jaffars** [LiveappSolutions/Liveapp#64]
iPad or iPhone - when it says 'Type here to Search' that I will be able to do so.  At the moment when i tap into a search field i am unable to search as the keyboard does not appear even after tapping the text field.

![image](https://user-images.githubusercontent.com/27175862/35492478-34cf915c-0501-11e8-8253-04647ff3cb3f.png)

**Comment by paulfisher53** [comment]
Hi @jaffars , please try this fix:

[Fix-64.zip](https://github.com/LiveappSolutions/Liveapp/files/1701470/Fix-64.zip)

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
