### ISSUE TITLE
DateTime field in mobile - no formatting

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#65]
Object: Page
Type: List
Device: Mobile

Currently the DateTime field on mobile has no formatting so will display in full including timezone.

Suggested Fix- 
Script - scripts/ui/MobileControls/grid.js
In the this.AddColumn function-

```
else if (field.Type == "DateTime") {
                m_cols.push({
                    name: field.Name,
                    align: "center",
                    onformat: function (val) {
                        if (val == null)
                            return "";
                        try {
                        return $.format.date(val, "dd/MM/yyyy hh:mm a");
                        } catch (e) {
                        }
                        return val;
                    }
                });
            }
```

**Comment by paulfisher53** [comment]
Hi @JasonBev , great solution! Here is the official fix:

[Fix-65.zip](https://github.com/LiveappSolutions/Liveapp/files/1701802/Fix-65.zip)

**Comment by JasonBev** [comment]
Cheers, testing complete and fix provided works as intended. 
Nothing further required for this item.

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
