### ISSUE TITLE
Mobile/Tablet View- Unable to type into anyvalue for search textbox

### ISSUE THREAD

**Issue by jaffars** [LiveappSolutions/Liveapp#68]
In desktop view for a lookup field, I can search for a value or type in any value for the field to be saved but in mobile/tablet view I can only search for a value.

Eg.
Desktop Flow - Lookup in the search box for an existing value or can type in any value I would like to enter
Mobile/Tablet - Lookup an existing value but no provision to type in new value

**Comment by paulfisher53** [comment]
Hi Jaffar,

In v5.3, I was able to enter a non-lookup value in mobile/tablet mode by clicking in the field, typing a value in, then hitting enter on my keyboard. 

Are you able to do the same?

**Comment by jaffars** [comment]
Thanks Paul,
Will close this once our QA team confirms after retesting.

**Comment by paulfisher53** [comment]
Closing the issue. If there is a problem, please re-open.
