### ISSUE TITLE
Grand Totals - Report grouping

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#70]
**Script:** report.js

**Request:** For default reports to have a grand total option when using groupfields option. Currently provides a total for each grouping when what field is set in groupfields changes. Grand total would be for all groups combined.

**Additional:** Adding new grand total row to export to default CSV functionality also

**Comment by paulfisher53** [comment]
Hi Jason,

Please load this mod: [Fix-70.zip](https://github.com/ZoomApps/Liveapp/files/1809617/Fix-70.zip)

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
