### ISSUE TITLE
Tablet View - Getting Error when opening using new OptionsWindow({ code

### ISSUE THREAD

**Issue by jaffars** [LiveappSolutions/Liveapp#71]
Reproducible steps:-
1. Create page with grid
2. On selection of an item in a grid open edit page.
3. in the edit page have a custom action which will call new OptionsWindow({ code.

var options = new OptionsWindow({
      caption: 'Add Clients - ' + method,
      fields: [
        {Name: "Client", Caption: "Clients", Type: "BigText", LookupTable:"Clients", LookupField:"Client_ID", LookupFilters:"SORTING(FullName) WHERE(Client_ID=FILTER("+cids+"),CurrentlyExited=CONST(0),User Filter=CONST("+Application.Util.UserID()+"),CanView=CONST(1))", LookupColumns:"FullName", LookupColumnCaptions:"Name",CustomControl:"MultiSelect", Mandatory: true}
      ]
    });

4. Have a multi-select field to render.
5. On open the error reported will popup.

Based on the analysis the below piece of code in UI/MobileControl.js is causing the issue.This code is recently merged from liveapp framework.

this.Create = function (window_, container_, onchange_, setupfunc_) {

            //Save the control.
            m_container = container_;

            //Add the control to the window.
            window_.append(m_container);

            var scrollarea = $('html, body');
            if (m_viewer) {
                if( m_viewer.Dialog && m_viewer.Dialog()){
                    scrollarea = $("#"+m_viewer.ID());
                }else{
                    scrollarea = $("#"+m_viewer.ID()+"containerworkspace");
                }
            }

**The line of code which causes issue is - "scrollarea = $("#"+m_viewer.ID()+"containerworkspace");"** 

![image](https://user-images.githubusercontent.com/27175862/36187048-e1c40e78-1196-11e8-9252-aa80567d495c.png)

**Comment by paulfisher53** [comment]
Hi @jaffars in the UI/MobileControl.js script file, please change line 67 to:

```javascript
if (m_viewer && m_viewer.ID) {
```

**Comment by jaffars** [comment]
Hi Paul,

Changed the line and my preliminary testing seems to be good. Thanks for your quick turnaround.


if (m_viewer) {



to



if (m_viewer && m_viewer.ID) {


Jaffar Sadiq | B.COM(Commerce)|
Senior Software Developer |': 02 4921 8333 | 6: 02 4920 8500 |
www.liveware.com.au<http://www.liveware.com.au/> | Suite 9, 29 Smith Street Charlestown NSW 2290 |
[Liveware ERP Email Signature]

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
