### ISSUE TITLE
Xpress Change Log - Missing MOD entries for null values

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#72]
When an existing value in a non varchar field is modified to null, the relevant record isn't added to the change log.

Request: Have all modify actions recorded in this table for log purposes

**Comment by paulfisher53** [comment]
Hi @JasonBev try this fix: [Fix-72.zip](https://github.com/LiveappSolutions/Liveapp/files/1761334/Fix-72.zip)

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
