### ISSUE TITLE
Grid rows are not displaying for a specifix

### ISSUE THREAD

**Issue by jaffars** [LiveappSolutions/Liveapp#74]
The unknown issue causing to hide the review date Grid when logged in Via Windows Authentication.This is happening to the only specific user when logged in via windows account.This is not happening when we use form-based authentication for the same user.

Any insights from you would help me to identify what is wrong with the grid and why it's not displaying only for that user when logged into windows authentication

Note:- This site is running on old liveware platform

![image](https://user-images.githubusercontent.com/27175862/37011277-861e5d78-2143-11e8-9e9f-d230a5fcc91a.png)

**Comment by paulfisher53** [comment]
Sounds like the columns are hidden for that user (the windows and forms auth are actually 2 different liveapp users).

Try logging in via windows auth, and right click the grid header. This will bring up a list of columns (and will allow you to show the hidden ones)

**Comment by jaffars** [comment]
Yes you are rights, When I inspected the elements I could able to see display=none for those columns. I am not sure why this is happening so only for windows login.

**Comment by paulfisher53** [comment]
Did you right click and re-show the columns?

**Comment by jaffars** [comment]
can be closed
