### ISSUE TITLE
Dashboard custom caption

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#75]
Request: Ability to modify Dashboard caption for menu item/tab without framework changes -  i.e ability to edit 'home' constant in language file

**Comment by paulfisher53** [comment]
Done. [Fix-75.zip](https://github.com/ZoomApps/Liveapp/files/1809672/Fix-75.zip)

It uses the S_HOME language variable.

Remember to restart your app pool after changing the language file

**Comment by JasonBev** [comment]
Thanks, works as intended. 

As a client we are now able to customize the menu and tab display captions for 'Dashboard'

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
