### ISSUE TITLE
Menu Items not referencing ClientCaption + ProgramCaption

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#76]
Prior to LiveApp 5.0 the application menu item captions for Liveware would reflect what was entered into the company table fields for-

ClientCaption
ProgramCaption

Now they are hard-coded to 'clients' and 'programs'.

**Comment by paulfisher53** [comment]
Please load this fix: [Fix-76.zip](https://github.com/ZoomApps/Liveapp/files/1930196/Fix-76.zip)

**Comment by JasonBev** [comment]
Issue resolved

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
