### ISSUE TITLE
Tracking of device login

### ISSUE THREAD

**Issue by jaffars** [LiveappSolutions/Liveapp#77]
There is no way to find out from which devices it is logged-in from live app framework.We require a column in [Xpress Session Event] table to identify the device like Desktop, Mobile, and Tablet

**Comment by paulfisher53** [comment]
Done. Please load the `Objects` from this fix first (using the `Object Designer`), then load the `Web Service` files.

[Fix-77.zip](https://github.com/ZoomApps/Liveapp/files/1930256/Fix-77.zip)

**Comment by jaffars** [comment]
Hi Paul,

The fix is working but when i run the report i could not able to filter by screen type.Can you add screen type as part of Session Events report filter.

thanks
Jaffar

**Comment by paulfisher53** [comment]
Hi @jaffars ,

Please load this page to get the new filter: [PAGE Session Events.zip](https://github.com/ZoomApps/Liveapp/files/1949344/PAGE.Session.Events.zip)

**Comment by jaffars** [comment]
Fix provided working

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
