### ISSUE TITLE
Double refresh required to load all resources after new version Update

### ISSUE THREAD

**Issue by jaffars** [LiveappSolutions/Liveapp#78]
We have identified an issue after new version upgrade of liveapp framework 5.2.

The user has to do a double refresh to load all the resource/images required for the page after a fresh installation.

Note : - Once the installation is completed and after a double refresh for any further updates we only been asked to do one refresh.

**Comment by paulfisher53** [comment]
Hi Jaffar,

Is the site external? If so, can you send me the URL so I can check the debugger

**Comment by jaffars** [comment]
Can you try this URL.This is a cloud.

https://cims.livewarecloud.com.au/ascent

Jaffar Sadiq | B.COM(Commerce)|
Senior Software Developer |': 02 4921 8333 | 6: 02 4920 8500 |
www.liveware.com.au<http://www.liveware.com.au/> | Suite 9, 29 Smith Street Charlestown NSW 2290 |
[Liveware ERP Email Signature]

**Comment by paulfisher53** [comment]
Looks like the service worker did not handle 'default' instances. I have added a fix so that a slash (/) is added to the end of the URL when using the 'default' instance.

[Fix-78.zip](https://github.com/ZoomApps/Liveapp/files/2056565/Fix-78.zip)

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
