### ISSUE TITLE
Allow to ignore the Customised field

### ISSUE THREAD

**Issue by adamLiveware** [LiveappSolutions/Liveapp#8]
Sometimes we need to update all objects in a solution, even if they are customised. Currently we need to update the field on every object. It would be desirable to have a way to override this behaviour so we don't have to do this update. Mostly we will use this in build scripts so we need it mostly for the console, but ideally it should be available in the GUI as well.

**Comment by paulfisher53** [comment]
Added a new web service function "SolutionUpdateForce". Please load [Patch.zip](https://github.com/LiveappSolutions/Liveapp/files/836990/Patch.zip)

To call from your script:
``` javascript
Application.ExecuteWebService("SolutionUpdateForce", { auth: Application.auth, url_: "SOLUTION_URL"});
```
We will be adding this function to the GUI in the next version.
