### ISSUE TITLE
Request/Idea - Special character "&" is causing issues in Framework

### ISSUE THREAD

**Issue by jaffars** [LiveappSolutions/Liveapp#80]
Recently we have noticed quite a few issues popped out due to "&" special character in the data.For some reason, in a field, if a "& " presents the query is formed wrongly and no data is retrieved.

Could you able to throw a warning for the User in the framework stating "&" special characters are not allowed.This will help us to resolve the issue caused by data, Sometimes it becomes very hard to identify the root cause of the issue since no error being thrown.

**Comment by paulfisher53** [comment]
Hi Jaffar,

Rather than stopping input of the ampersand character, I have added a fix to the filtering module in system. Please give it try with this fix: [Fix-80.zip](https://github.com/ZoomApps/Liveapp/files/2029682/Fix-80.zip)

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
