### ISSUE TITLE
Xpress User Layout table performance

### ISSUE THREAD

**Issue by paulfisher53** [LiveappSolutions/Liveapp#82]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

High CPU usage for some SQL queries. Seems to be caused by missing indexes on the `Xpress User Layout` table.

**Expected / new behavior:**

Lower CPU usage for the User Layout query.

**Minimal reproduction of the problem with instructions:**

In SQL management studio, check the most recent expensive queries. The following query is shown:

```sql
(@1 varchar(8000),@2 varchar(8000))SELECT [Layout] FROM [Xpress User Layout] WHERE [Username]=@1 AND [Page Name]=@2
```

**Liveapp version:** 5.4.0

**Browser:** all

**Anything else:**

Please add an index to the "Xpress User Layout" table:

Columns: Username, Page Name
Include: Layout

**Comment by paulfisher53** [comment]
Done. Please load fix: [Fix-82.zip](https://github.com/ZoomApps/Liveapp/files/1930181/Fix-82.zip)

@jaffars Can you please load this for Adam?

**Comment by jaffars** [comment]
Hi Paul,

Will this fix will be available as part of next liveapp release.Since this is a liveapp solution file.

**Comment by paulfisher53** [comment]
Hi @jaffars ,

Yeah, this fix will be released at the end of the month via the System solution.

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
