### ISSUE TITLE
Allow to suppress update popups

### ISSUE THREAD

**Issue by adamLiveware** [LiveappSolutions/Liveapp#9]
As a super user, I would like to be able to suppress the update popups for solutions and framework because I never use them and always dismiss them. This is not a critical issue, just a bit of an annoyance.

**Comment by paulfisher53** [comment]
Added a new web service function "SolutionUpdateForce". Please load [Patch.zip](https://github.com/LiveappSolutions/Liveapp/files/836990/Patch.zip)

To call from your script:
``` javascript
Application.ExecuteWebService("SolutionUpdateForce", { auth: Application.auth, url_: "SOLUTION_URL"});
```
We will be adding this function to the GUI in the next version.

**Comment by paulfisher53** [comment]
Done. Please load [Patch.zip](https://github.com/LiveappSolutions/Liveapp/files/836992/Patch.zip)

Set the setting "CHECK_UPDATES" in web.config setting to FALSE
