### ISSUE TITLE
Issue when trying to delete a staff from the roster staff page.

### ISSUE THREAD

**Issue by LIvewareNB** [LiveappSolutions/Liveapp#93]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
When you select a user in the Roster Staff Page it is not returning the correct User ID / the selected row is not pulling and returning the correct User ID on the edit code section

**Expected / new behavior:**
If a staff member has no shifts assigned to them on a roster they should be able to be deleted from the roster

**Minimal reproduction of the problem with instructions:**
1. Log into UAT site and go to a roster Roster Staff Page.
2. Select a user then try and delete it. 
3. It should return the correct User ID

An Example of the issue (using https://cims.livewarecloud.com.au/uatliveappv5_17/) is John Smith has a user ID of 50
![Liveapp Roster staff 1](https://user-images.githubusercontent.com/54254246/64224533-43331a80-cf1b-11e9-9068-8f9b913f21f2.png)

John Smith is selected however the User ID returned by liveapp is 13. Note: it happens to all users not on new users only
![Liveapp Roster staff 2](https://user-images.githubusercontent.com/54254246/64224621-94430e80-cf1b-11e9-811d-787568b4d209.png)

**Liveapp version:** 5.6.0 and 6.0.0 please access https://cims.livewarecloud.com.au/UAT/#  and https://cims.livewarecloud.com.au/uatliveappv5_17/

**Browser:** Chrome

**Anything else:**

**Comment by paulfisher53** [comment]
Hi @LIvewareNB , the issue here is that you are using the Delete button trigger which runs after the record is deleted. If you want to run code before it is deleted, you need to move your code to the `OnDelete` trigger on the Table.

**Comment by paulfisher53** [comment]
**Fix/mod is available for this issue**

We are closing this issue as a fix/mod has been supplied. 

**NOTE:** If the issue persists, please re-open the issue with the appropriate testing information.
